version: "3.9"

services:
  db:
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=simple-poll
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Welcome01!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings:SimplePoll=Server=db; Database=simple-poll; User Id=postgres; Password=postgres;
    volumes:
      - ~/.aspnet/https:/https:ro
  dbmigrations:
    environment:
      - ConnectionSettings:Server=db