version: "3.9"

services:
  db:
    image: postgres
  api:
    build:
      context: .
      dockerfile: src/SimplePoll.Api/Dockerfile
    depends_on:
      - db
      - dbmigrations
  dbmigrations:
    build:
      context: .
      dockerfile: src/SimplePoll.Migrations/Dockerfile
    depends_on:
      - db